version: '3.5'

services:
  app:
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://admin:adminadmin@pg:5432/blog
      CONFIG_NAME: DevConfig
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./blog:/app/blog
    ports:
      - 5000:5000
    command: bash -c "
      ./wait-for-postgres.sh pg
      && flask db init 
      && flask db migrate 
      && flask db upgrade
      && flask create-user
      && flask create-article
      && python wsgi.py"
    depends_on:
      - pg

  pg:
    image: postgres:12
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminadmin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - pg
